version: '3'

services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fobar
    volumes:
      - db_data:/var/lib/postgressql/data/
volumes:
  db_data: